name: notetodo_app
description: A Note + Todo App
publish_to: 'none'

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Database
  sqflite: ^2.2.8+4
  path: ^1.8.3

  # Lottie animation
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/loading.json